#local, dev, prod 공통 설정
#profiles 선언하여 적용할 profile을 선택한다.
spring:
  profiles:
    active: local

---
#local 환경
spring:
  profiles: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://smileway.co.kr:3306/bizmiso?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: bizmiso
    password: Miso@7531

# Mybatis
mybatis:
  type-aliases-package: com.misonamoo.niaportal.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  map-underscore-to-camel-case: true

# Logback 위치 지정
logging:
  config: classpath:logback-default.xml

---
#dev 환경
spring:
  profiles: dev
  datasource: #TODO: dev용으로 변경 필요
  url:
  hikari:
    username:
    password:

---
#prod 환경
spring:
  profiles: prod
  datasource: #TODO : prod용으로 변경 필요
    url:
    hikari:
      username:
      password:
server:
  port: 9090